runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

env_variables:
  FLASK_APP: 'main.py'
  FLASK_DEBUG: '1'
  PYTHONHTTPSVERIFY: 1
  MONKEY_PATCH: 1

libraries:
- name: ssl
  version: 2.7.11